#!/usr/bin/env bash
# script to archive all MySQL DATABASE with the assistance from mysqldump and tar
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
